const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

module.exports = {
  "SESSION_ID": process.env.SESSION_ID || ""SESSION_ID": "eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiU0VXb2NmTW0rZUJsTGJYMzdzckNiREZPVnBIcWh3Q2JvNnJHYW5PSk9uTT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZ2czU0tXT2pRYnJ3dE0vZ05tVFRVbTdSMWhEQ2hZVFhId29iVGQ2d3QwTT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJlQWp2TGgzWTFNdktKRnJqRldWazNlK1Z0SmRnbndhZS9sRUNEaW5iSDJRPSJ9LCJwdWJpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6JnZXoY2VzZEF2bWJHYW5FOGN0VmJjUEIvOTZscGNFeHpDNWRsWFBkYm5ZPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImlMdlNXRFlpaWcvdUZmWEg0QzZMckx5WlZVUC94ZVk4YWlzWnQ3M3lsSGc9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkN2WkNzNXBRUlFMbDl1U0t6UGQ2WXpUN3RJT2VzaTFCai8zU2hHTThxRkk9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoieUdSN2N2elRFVzVpUGVGcmQ3WlVMaVNRYnhhdkxvaGpza0MyRmZPWFZFVT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiOXIrNDJTNXdRbktaNDY2SDJGdFV0VFVIS2hrYTM2Uk5yZ0U5Q2RDVkxrYz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkphZ2wrcFdFMTBnZEN1UUg5QUtwS0hiS2dITkpqbjN2aytrMnVDUVhWTEVJeEptWHBKTzlDMnBzamF2akdqdlNWVjBkM0syMkxxM2xMaHJlR0U2amlBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTI4LCJhZHZTZWNyZXRLZXkiOiJWY3VPTHBETUc1U3JKU3JsNU9nazRXcWVZTXBjVFFGdVQwRGtXTGl5SndVPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwicmVnaXN0ZXJlZCI6ZmFsc2UsImFjY291bnQiOnsiZGV0YWlscyI6IkNLZVBtUHdCRVBqQXFzMEdHQUVnQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiI5VGVrZmwrQnMxdXFCa3N4QTJRaDRIV3h1clRkNXU5cXNjbXR4c3RLT0VZPSIsImFjY291bnRTaWduYXR1cmUiOiJjRytSRWZpN3UzSW00bWdBVUdhcWhhTFlMYnVDNmozampoRHlmK1VidmFieXZYVjlhMkJMckY2MVpXQ1VuSytUTmtyRVk4N1lTazdPSHV6L2lVdlFEdz09IiwiZGV2aWNlU2lnbmF0dXJlIjoiZG1IZm1HSUlVVFU3eUlvREw3aXVtSmZJcWFMektuMXNCbGZqbjA5N2pnM2xQV3dBdG5xTHUxTXRzS01CQ1c2c015Z3lGWW4yNHd6NkhVKzJjUUhDZ1E9PSJ9LCJtZSI6eyJpZCI6IjI1NTc5Mzc3MDczMTo3QHMud2hhdHNhcHAubmV0IiwibmFtZSI6IktpbmciLCJsaWQiOiIyMzA5MjM4OTk1Mzk0NTY6N0BsaWQifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjU1NzkzNzcwNzMxOjdAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCZlUzcH5mZmdiTmJxZ1pMTVFOa0llQjFzYnEwM2VidmFySEpyY2JMU2poRyJ9fV0sInBsYXRmb3JtIjoic21iYSIsInJvdXRpbmdJbmZvIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQ0FVSURRZ0kifSwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzcyNzg5ODkxLCJsYXN0UHJvcEhhc2giOiJubTNCYiIsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBT3NVIn0=",
  "ALIVE_IMG": process.env.ALIVE_IMG || "https://raw.githubusercontent.com/HyHamza/HyHamza/refs/heads/main/Images/logo.jpg",
  "PREFIX": process.env.PREFIX || ".",
  "AUTO_READ_STATUS": process.env.AUTO_READ_STATUS === 'true',
  "MODE": process.env.MODE || "public",
  "OWNER_NUMBER": process.env.OWNER_NUMBER || "255793770731",
  "OWNER_NAME": process.env.OWNER_NAME || "GILBMOSHA BOT",
  "ALWAYS_ONLINE": process.env.ALWAYS_ONLINE === 'true',
  "PRESENCE": process.env.PRESENCE || "online",
  "OMDB_API_KEY": process.env.OMDB_API_KEY || "76cb7f39",
  "READ_CMD": process.env.READ_CMD === 'true',
  "AUTO_VOICE": process.env.AUTO_VOICE === 'true',
  "AUTO_STICKER": process.env.AUTO_STICKER === 'true',
  "AUTO_REPLY": process.env.AUTO_REPLY === 'true',
  "AUTO_REACT": process.env.AUTO_REACT === 'true',
  "WELCOME": process.env.WELCOME === 'true',
  "ANTI_BAD": process.env.ANTI_BAD === 'true',
  "ANTI_LINK": process.env.ANTI_LINK === 'true',
  "ANTI_GROUP_LINK": process.env.ANTI_GROUP_LINK === 'true',
  "ANTI_DELETE": process.env.ANTI_DELETE === 'true',
  "ANTI_VIEW_ONCE": process.env.ANTI_VIEW_ONCE === 'true',
  "ANTI_BOT": process.env.ANTI_BOT === 'true',
  "PREMIUM_USERS": process.env.PREMIUM_USERS || "",
  "COUNTRY_BLOCK": process.env.COUNTRY_BLOCK === 'true',
  "COUNTRY_BLOCK_CODE": process.env.COUNTRY_BLOCK_CODE || "972",
  "EMOJI": process.env.EMOJI || "🙄",
  "AUTO_TYPING": process.env.AUTO_TYPING === 'true'
};
